[package]
name = "depends"
version = "0.1.0"
edition = "2021"
description = "Ergonomic, performant, incremental computation between arbitrary types"
license = "MIT"
repository = "https://github.com/Justice4Joffrey/depends-rs"
keywords = ["dag", "graph", "incremental", "computation", "cache"]
readme = "../README.md"

[dependencies]
depends_core = {path = "../depends_core", version = "0.1.0"}
depends_derives = {path = "../depends_derives", version = "0.1.0"}

[features]
default = []
graphviz = []
hashbrown = ["depends_core/hashbrown"]

