[book]
language = "en"
multilingual = false
src = "src"
title = "Incremental Computation with Depends"

[output.html.playground]
runnable = false

[output.linkcheck]
follow-web-links = true
warning-policy = "error"
